export const colors = {
  primary: '#CC0000',
  primaryLight: '#E8001C',
  primaryBg: '#FFE8E8',
  danger: '#9B1C1C',
  dangerBg: '#FEE2E2',
  success: '#16a34a',
  successBg: '#dcfce7',
  border: '#E8D0D0',
  text: '#1a1a1a',
  textMuted: '#6B4C4C',
  bg: '#FDF5F5',
  white: '#ffffff',
};

export const s = {
  card: {
    background: colors.white,
    borderRadius: '12px',
    border: `1px solid ${colors.border}`,
    padding: '1rem 1.25rem',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    boxShadow: '0 1px 3px rgba(204,0,0,0.07)',
  },
  form: {
    background: colors.white,
    borderRadius: '12px',
    border: `2px solid ${colors.primaryLight}`,
    padding: '1.25rem',
    marginBottom: '1.25rem',
    boxShadow: '0 4px 12px rgba(204,0,0,0.09)',
  },
  label: {
    display: 'block',
    fontSize: '0.8rem',
    fontWeight: 600,
    color: colors.textMuted,
    marginBottom: '0.35rem',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  input: (hasError) => ({
    width: '100%',
    padding: '0.6rem 0.8rem',
    borderRadius: '8px',
    border: `1.5px solid ${hasError ? colors.danger : colors.border}`,
    fontSize: '0.9rem',
    color: colors.text,
    background: hasError ? '#fff0f0' : colors.white,
    outline: 'none',
    boxSizing: 'border-box',
  }),
  errorText: {
    color: colors.danger,
    fontSize: '0.75rem',
    margin: '0.25rem 0 0',
  },
  addBtn: {
    background: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: '8px',
    padding: '0.55rem 1.1rem',
    fontWeight: 600,
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  cancelBtn: {
    background: '#f5eded',
    color: colors.textMuted,
    border: 'none',
    borderRadius: '8px',
    padding: '0.55rem 1.1rem',
    fontWeight: 600,
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  submitBtn: {
    background: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: '8px',
    padding: '0.65rem 1.5rem',
    fontWeight: 700,
    fontSize: '0.9rem',
    cursor: 'pointer',
    marginTop: '0.75rem',
  },
  deleteBtn: {
    background: colors.dangerBg,
    color: colors.danger,
    border: 'none',
    borderRadius: '8px',
    padding: '0.45rem 0.85rem',
    fontWeight: 600,
    fontSize: '0.8rem',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  badge: (color = colors.primaryBg, text = colors.primary) => ({
    background: color,
    color: text,
    borderRadius: '999px',
    padding: '0.15rem 0.6rem',
    fontSize: '0.75rem',
    fontWeight: 600,
  }),
  empty: {
    textAlign: 'center',
    padding: '3rem 1rem',
    color: colors.textMuted,
    background: colors.white,
    borderRadius: '12px',
    border: `1px dashed ${colors.border}`,
    fontSize: '1rem',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  h2: {
    margin: 0,
    color: colors.text,
    fontSize: '1.2rem',
    fontWeight: 700,
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '1rem',
  },
  stack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
};
