// QFlow Design System tokens — sourced from design-system/colors_and_type.css
// Use these constants in all inline styles. Never hardcode raw hex values.

export const QF = {
  // Brand
  red500:   '#E11D2C',
  red600:   '#C00C1F',
  red50:    '#FFF1F1',
  red100:   '#FFE0E0',
  red300:   '#FF9090',
  red700:   '#9B0518',
  // Surfaces & lines
  bg:       '#FBF7F7',
  surface:  '#FFFFFF',
  surface2: '#FAF3F3',
  line:     '#EFE0E0',
  line2:    '#E2D2D2',
  // Text
  fg1:      '#1A1414',
  fg2:      '#4D3838',
  fg3:      '#8A6F6F',
  fg4:      '#B59A9A',
  // Semantic
  danger:      '#B91C1C',
  dangerSoft:  '#FEE2E2',
  success:     '#14B8A6',
  successSoft: '#CFFAF1',
  warning:     '#F59E0B',
  warningSoft: '#FEF3C7',
  violet:      '#7C3AED',
  violetSoft:  '#EDE9FE',
  // Typography
  font: "'Heebo','Segoe UI','Arial Hebrew',system-ui,sans-serif",
  // Motion
  ease:   'cubic-bezier(0.22,1,0.36,1)',
  dur:    '220ms',
  // Shadows (red-tinted warm)
  shadow1: '0 1px 2px rgba(180,12,31,0.06)',
  shadow2: '0 4px 14px rgba(180,12,31,0.09), 0 1px 2px rgba(0,0,0,0.04)',
  shadow3: '0 14px 40px rgba(180,12,31,0.14), 0 2px 6px rgba(0,0,0,0.05)',
  glow:    '0 0 0 6px rgba(225,29,44,0.16), 0 8px 28px rgba(225,29,44,0.28)',
  // Gradients
  grad3d: 'radial-gradient(120% 100% at 30% 20%, #FF7E7E 0%, #E11D2C 38%, #9B0518 78%, #420009 100%)',
};

// Backward-compat alias used across view files
export const colors = {
  primary:     QF.red500,
  primaryLight: QF.red600,
  primaryBg:   QF.red50,
  danger:      QF.danger,
  dangerBg:    QF.dangerSoft,
  success:     QF.success,
  successBg:   QF.successSoft,
  border:      QF.line,
  text:        QF.fg1,
  textMuted:   QF.fg2,
  bg:          QF.bg,
  white:       QF.surface,
};

// Shared style objects
export const s = {
  card: {
    background:   QF.surface,
    borderRadius: '14px',
    border:       `1px solid ${QF.line}`,
    padding:      '14px 18px',
    display:      'flex',
    alignItems:   'center',
    gap:          '14px',
    boxShadow:    QF.shadow1,
    transition:   `box-shadow 220ms ${QF.ease}`,
  },
  form: {
    background:   QF.surface,
    borderRadius: '14px',
    border:       `2px solid ${QF.red300}`,
    padding:      '1.25rem',
    marginBottom: '1.25rem',
    boxShadow:    QF.shadow2,
  },
  label: {
    display:       'block',
    fontSize:      '11px',
    fontWeight:    600,
    color:         QF.fg3,
    marginBottom:  '6px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  input: (hasError) => ({
    width:       '100%',
    padding:     '10px 12px',
    borderRadius: '10px',
    border:      `1.5px solid ${hasError ? QF.danger : QF.line}`,
    fontSize:    '14px',
    fontFamily:  QF.font,
    color:       QF.fg1,
    background:  hasError ? '#fff5f5' : QF.surface,
    outline:     'none',
    boxSizing:   'border-box',
    transition:  'border-color 150ms, box-shadow 150ms',
  }),
  errorText: {
    color:     QF.danger,
    fontSize:  '11px',
    margin:    '4px 0 0',
  },
  addBtn: {
    background:   QF.red500,
    color:        '#fff',
    border:       'none',
    borderRadius: '10px',
    padding:      '10px 18px',
    fontWeight:   700,
    fontSize:     '14px',
    cursor:       'pointer',
    display:      'inline-flex',
    alignItems:   'center',
    gap:          '6px',
    boxShadow:    QF.shadow2,
    transition:   `all 220ms ${QF.ease}`,
  },
  cancelBtn: {
    background:   QF.surface2,
    color:        QF.fg2,
    border:       'none',
    borderRadius: '10px',
    padding:      '10px 18px',
    fontWeight:   600,
    fontSize:     '14px',
    cursor:       'pointer',
    display:      'inline-flex',
    alignItems:   'center',
    gap:          '6px',
    transition:   `all 220ms ${QF.ease}`,
  },
  submitBtn: {
    background:   QF.red500,
    color:        '#fff',
    border:       'none',
    borderRadius: '10px',
    padding:      '10px 22px',
    fontWeight:   700,
    fontSize:     '14px',
    cursor:       'pointer',
    marginTop:    '12px',
    display:      'inline-flex',
    alignItems:   'center',
    gap:          '6px',
    boxShadow:    QF.shadow2,
    transition:   `all 220ms ${QF.ease}`,
  },
  deleteBtn: {
    background:   QF.dangerSoft,
    color:        QF.danger,
    border:       'none',
    borderRadius: '10px',
    padding:      '8px 14px',
    fontWeight:   600,
    fontSize:     '13px',
    cursor:       'pointer',
    whiteSpace:   'nowrap',
    display:      'inline-flex',
    alignItems:   'center',
    gap:          '5px',
    transition:   `all 220ms ${QF.ease}`,
  },
  badge: (bg = QF.red50, fg = QF.red500) => ({
    background:   bg,
    color:        fg,
    borderRadius: '999px',
    padding:      '3px 10px',
    fontSize:     '11px',
    fontWeight:   700,
    whiteSpace:   'nowrap',
    display:      'inline-flex',
    alignItems:   'center',
    gap:          '5px',
  }),
  empty: {
    textAlign:    'center',
    padding:      '3rem 1rem',
    color:        QF.fg2,
    background:   QF.surface,
    borderRadius: '14px',
    border:       `1px dashed ${QF.line2}`,
    fontSize:     '1rem',
  },
  pageHeader: {
    display:        'flex',
    justifyContent: 'space-between',
    alignItems:     'center',
    marginBottom:   '1rem',
  },
  h2: {
    margin:     0,
    color:      QF.fg1,
    fontSize:   '1.2rem',
    fontWeight: 700,
  },
  grid2: {
    display:             'grid',
    gridTemplateColumns: '1fr 1fr',
    gap:                 '1rem',
  },
  grid3: {
    display:             'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap:                 '1rem',
  },
  stack: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '10px',
  },
};
